services:
  - type: web
    name: n8n
    env: docker
    plan: starter  # puedes usar free, pero se duerme después de 15 min
    region: oregon # o usa "virginia" si estás en la costa este
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        value: supersegura123
      - key: N8N_HOST
        value: n8n.onrender.com
      - key: N8N_PORT
        value: 5678
      - key: WEBHOOK_URL
        value: https://n8n.onrender.com/
